#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const { getConfigParser } = require("./utils");

/**
 * Tạo file JavaScript chứa build info với merge logic
 */
function createBuildInfoJS(buildInfo) {
  return `
// Auto-generated by cordova-plugin-change-app-info
// Build Time: ${buildInfo.buildTime}

(function() {
  'use strict';
  
  var newBuildInfo = ${JSON.stringify(buildInfo, null, 2)};
  
  // Wait for deviceready
  document.addEventListener('deviceready', function() {
    try {
      // Đọc dữ liệu cũ từ localStorage
      var existingDataStr = localStorage.getItem('APP_BUILD_INFO');
      var existingData = existingDataStr ? JSON.parse(existingDataStr) : {};
      
      // Preserve các field quan trọng từ data cũ
      var preservedData = {
        firstInstallTime: existingData.firstInstallTime || newBuildInfo.buildTime,
        firstInstallVersion: existingData.firstInstallVersion || newBuildInfo.versionNumber,
        installCount: (existingData.installCount || 0) + 1,
        
        // User data (nếu có)
        userData: existingData.userData || {},
        userSettings: existingData.userSettings || {},
        lastActiveTime: existingData.lastActiveTime || null
      };
      
      // Detect update
      var isUpdate = existingData.versionNumber && 
                     existingData.versionNumber !== newBuildInfo.versionNumber;
      
      if (isUpdate) {
        preservedData.lastUpdateTime = new Date().toISOString();
        preservedData.previousVersion = existingData.versionNumber;
        preservedData.previousVersionCode = existingData.versionCode;
        console.log('[Build Info] Update detected:', existingData.versionNumber, '→', newBuildInfo.versionNumber);
      }
      
      // Merge: Build info mới + Preserved data
      var mergedBuildInfo = Object.assign({}, newBuildInfo, preservedData);
      
      // Lưu lại
      localStorage.setItem('APP_BUILD_INFO', JSON.stringify(mergedBuildInfo));
      
      // Set global variable
      window.APP_BUILD_INFO = mergedBuildInfo;
      
      console.log('[Build Info] Loaded and merged:', mergedBuildInfo);
      console.log('[Build Info] API Hostname:', mergedBuildInfo.apiHostname);
      console.log('[Build Info] First install:', preservedData.firstInstallVersion, 'at', preservedData.firstInstallTime);
      console.log('[Build Info] Install count:', preservedData.installCount);
      
    } catch (e) {
      console.error('[Build Info] Failed to save:', e);
    }
  }, false);
  
  // Helper function to update user data without losing build info
  window.updateAppUserData = function(key, value) {
    try {
      var buildInfo = JSON.parse(localStorage.getItem('APP_BUILD_INFO') || '{}');
      if (!buildInfo.userData) {
        buildInfo.userData = {};
      }
      buildInfo.userData[key] = value;
      buildInfo.lastActiveTime = new Date().toISOString();
      localStorage.setItem('APP_BUILD_INFO', JSON.stringify(buildInfo));
      window.APP_BUILD_INFO = buildInfo;
      console.log('[Build Info] User data updated:', key);
    } catch (e) {
      console.error('[Build Info] Failed to update user data:', e);
    }
  };
  
  // Helper function to update user settings
  window.updateAppSettings = function(settings) {
    try {
      var buildInfo = JSON.parse(localStorage.getItem('APP_BUILD_INFO') || '{}');
      buildInfo.userSettings = Object.assign(buildInfo.userSettings || {}, settings);
      buildInfo.lastActiveTime = new Date().toISOString();
      localStorage.setItem('APP_BUILD_INFO', JSON.stringify(buildInfo));
      window.APP_BUILD_INFO = buildInfo;
      console.log('[Build Info] Settings updated');
    } catch (e) {
      console.error('[Build Info] Failed to update settings:', e);
    }
  };
  
})();
`;
}

/**
 * Inject build info vào www folder
 */
function injectBuildInfo(context, platform) {
  const root = context.opts.projectRoot;
  
  // Đọc config
  const config = getConfigParser(context, path.join(root, "config.xml"));
  
  // Đọc hostname từ config
  const apiHostname = config.getPreference("API_HOSTNAME") || "";
  const apiBaseUrl = config.getPreference("API_BASE_URL") || "";
  const environment = config.getPreference("ENVIRONMENT") || "production";
  
  const buildInfo = {
    // Build info (sẽ được update mỗi build)
    appName: config.getPreference("APP_NAME") || config.name() || "Unknown",
    versionNumber: config.getPreference("VERSION_NUMBER") || config.version() || "0.0.0",
    versionCode: config.getPreference("VERSION_CODE") || "0",
    packageName: config.packageName() || "unknown",
    platform: platform,
    buildTime: new Date().toISOString(),
    buildTimestamp: Date.now(),
    
    // API Configuration (có thể thay đổi theo environment)
    apiHostname: apiHostname,
    apiBaseUrl: apiBaseUrl,
    environment: environment,
    
    // CDN Info (optional)
    cdnIcon: config.getPreference("CDN_ICON") || null
    
    // firstInstallTime, firstInstallVersion, userData, userSettings
    // sẽ được preserve từ localStorage cũ
  };
  
  // Đường dẫn www của platform
  let wwwPath;
  if (platform === "android") {
    wwwPath = path.join(root, "platforms/android/app/src/main/assets/www");
  } else if (platform === "ios") {
    wwwPath = path.join(root, "platforms/ios/www");
  } else {
    console.log(`⚠️ Platform ${platform} not supported for build info injection`);
    return;
  }
  
  if (!fs.existsSync(wwwPath)) {
    console.log(`⚠️ WWW path not found: ${wwwPath}`);
    return;
  }
  
  // Tạo file build-info.js
  const buildInfoPath = path.join(wwwPath, "build-info.js");
  const jsContent = createBuildInfoJS(buildInfo);
  
  fs.writeFileSync(buildInfoPath, jsContent, "utf8");
  console.log(`✅ Build info injected to: ${buildInfoPath}`);
  console.log(`   App: ${buildInfo.appName} v${buildInfo.versionNumber} (${buildInfo.versionCode})`);
  console.log(`   Environment: ${buildInfo.environment}`);
  console.log(`   API Hostname: ${buildInfo.apiHostname || 'Not configured'}`);
  console.log(`   API Base URL: ${buildInfo.apiBaseUrl || 'Not configured'}`);
  console.log(`   Build: ${buildInfo.buildTime}`);
  console.log(`   Note: User data and install history will be preserved`);
  
  // Thêm script tag vào index.html
  injectScriptTag(wwwPath, "build-info.js");
}

/**
 * Thêm <script> tag vào index.html
 */
function injectScriptTag(wwwPath, scriptFile) {
  const indexPath = path.join(wwwPath, "index.html");
  
  if (!fs.existsSync(indexPath)) {
    console.log("⚠️ index.html not found");
    return;
  }
  
  let html = fs.readFileSync(indexPath, "utf8");
  
  // Check xem đã có script tag chưa
  if (html.includes(scriptFile)) {
    console.log("   Script tag already exists in index.html");
    return;
  }
  
  // Thêm script tag trước </head> hoặc trước cordova.js
  const scriptTag = `    <script src="${scriptFile}"></script>`;
  
  // Ưu tiên thêm trước cordova.js
  if (html.includes('cordova.js')) {
    html = html.replace(
      /<script[^>]*src=["']cordova\.js["'][^>]*><\/script>/,
      `${scriptTag}\n    $&`
    );
  } else if (html.includes("</head>")) {
    html = html.replace("</head>", `${scriptTag}\n  </head>`);
  } else if (html.includes("</body>")) {
    html = html.replace("</body>", `${scriptTag}\n  </body>`);
  } else {
    console.log("⚠️ Could not find suitable location in index.html");
    return;
  }
  
  fs.writeFileSync(indexPath, html, "utf8");
  console.log(`   Added <script> tag to index.html`);
}

/**
 * Hook chính
 */
module.exports = function(context) {
  const platforms = context.opts.platforms;
  
  console.log("\n══════════════════════════════════");
  console.log("     INJECT BUILD INFO HOOK       ");
  console.log("══════════════════════════════════");
  
  for (const platform of platforms) {
    console.log(`\n📱 Processing ${platform}...`);
    injectBuildInfo(context, platform);
  }
  
  console.log("\n══════════════════════════════════");
  console.log("✅ Build info injection completed!");
  console.log("══════════════════════════════════\n");
};